name: Deploy Frontend to Google Cloud Storage

on:
  push:
    branches:
      - main 
    paths:
      - '../../^_^/rocketman-dupe-backend'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        credentials: ${{ secrets.GCLOUD_SA_KEY }}

    - name: Authenticate with Google Cloud
      run: |
        echo "${{ secrets.GCLOUD_SA_KEY }}" | base64 --decode > key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud config set project rocketman-contact-form

    - name: Deploy to Google Cloud Storage
      run: |
        gsutil -m rsync -r ./ gs://${{ secrets.BUCKET_NAME }}/
